known_generic_keywords:
  - personal loan
  - installment loan
  - bad credit loan
  - pet financing
  - vet financing
  - medical financing
  - dental financing
  - same day funding
  - emergency loan
  - prequalify loan
  - check your rate
  - soft credit check
